### ISSUE TITLE
Send POST data in body instead of params

### ISSUE THREAD

**Issue by leemartin** [icoretech/spotify-client#11]
Excuse me if this isn't obvious, but I just ran into a snag using the `add_user_tracks_to_playlist` function which throws a 414 when I'm sending too many songs over to it with params. (They end up being way too long) Is there anyway I can use this gem to send them via the BODY instead?

**Comment by masterkain** [comment]
hello,
I just pushed this (not released on rubygems yet) which might help fix the error, please reopen if it's still an issue. Sorry for being late.

https://github.com/icoretech/spotify-client/commit/79661418f7bbb3f6fde4fe51e00c27f75d0889a4
