### ISSUE TITLE
Replace Excon with RestClient

### ISSUE THREAD

**Issue by oleander** [icoretech/spotify-client#13]
Excon is using `Socket.getaddrinfo` for DNS lookups which is causing threads to freeze. This is discussed in excon/excon#159. This is a problem when using Sidekiq, something that's discussed here mperham/sidekiq#2012. One solution is to replace Excon with RestClient, as RestClient has its own DNS lookup.

Would a pull request implementing RestClient be accepted?

**Comment by DanielZwijnenburg** [comment]
Any news on this?

**Comment by oleander** [comment]
@DanielZwijnenburg I'm not sure on your motivation in regards to replacing Excon, but mine was related to sidekiq not working properly. I manage to solve it without changing this gem. Here's is my solution https://github.com/mperham/sidekiq/issues/2012#issuecomment-161084507
